package com.seysa.infrastructure.repository.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.util.DateUtils;

import java.util.Date;
import java.util.List;

@DynamoDBTable(tableName = "faces")
public class FaceItem implements Item {

    public static final String VIDEO_SCAN_ID_INDEX = "video_scan_id_index";
    private String id;
    private Date createdDate;
    private Date updatedDate;
    private String videoScanId;
    private Long timestamp;
    private String boundingBox;
    private Integer maxAge;
    private Integer minAge;
    private Boolean smile;
    private Boolean eyeglasses;
    private Boolean sunglasses;
    private String gender;
    private Boolean beard;
    private Boolean mustache;
    private Boolean eyeOpen;
    private Boolean mouthOpen;
    private List<String> emotions;
    private List<String> landmarks;
    private String pose;
    private String imageQuality;
    private Float confidence;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @Override
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "created_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @Override
    public Date getCreatedDate() {
        return DateUtils.cloneDate(createdDate);
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @DynamoDBAttribute(attributeName = "updated_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @Override
    public Date getUpdatedDate() {
        return DateUtils.cloneDate(updatedDate);
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    @DynamoDBAttribute(attributeName = "video_scan_id")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = VIDEO_SCAN_ID_INDEX)
    public String getVideoScanId() {
        return videoScanId;
    }

    public void setVideoScanId(String videoScanId) {
        this.videoScanId = videoScanId;
    }

    @DynamoDBAttribute(attributeName = "timestamp")
    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    @DynamoDBAttribute(attributeName = "bounding_box")
    public String getBoundingBox() {
        return boundingBox;
    }

    public void setBoundingBox(String boundingBox) {
        this.boundingBox = boundingBox;
    }

    @DynamoDBAttribute(attributeName = "max_age")
    public Integer getMaxAge() {
        return maxAge;
    }

    public void setMaxAge(Integer maxAge) {
        this.maxAge = maxAge;
    }

    @DynamoDBAttribute(attributeName = "min_age")
    public Integer getMinAge() {
        return minAge;
    }

    public void setMinAge(Integer minAge) {
        this.minAge = minAge;
    }

    @DynamoDBAttribute(attributeName = "smile")
    public Boolean getSmile() {
        return smile;
    }

    public void setSmile(Boolean smile) {
        this.smile = smile;
    }

    @DynamoDBAttribute(attributeName = "eyeglasses")
    public Boolean getEyeglasses() {
        return eyeglasses;
    }

    public void setEyeglasses(Boolean eyeglasses) {
        this.eyeglasses = eyeglasses;
    }

    @DynamoDBAttribute(attributeName = "sunglasses")
    public Boolean getSunglasses() {
        return sunglasses;
    }

    public void setSunglasses(Boolean sunglasses) {
        this.sunglasses = sunglasses;
    }

    @DynamoDBAttribute(attributeName = "gender")
    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @DynamoDBAttribute(attributeName = "beard")
    public Boolean getBeard() {
        return beard;
    }

    public void setBeard(Boolean beard) {
        this.beard = beard;
    }

    @DynamoDBAttribute(attributeName = "mustache")
    public Boolean getMustache() {
        return mustache;
    }

    public void setMustache(Boolean mustache) {
        this.mustache = mustache;
    }

    @DynamoDBAttribute(attributeName = "eye_open")
    public Boolean getEyeOpen() {
        return eyeOpen;
    }

    public void setEyeOpen(Boolean eyeOpen) {
        this.eyeOpen = eyeOpen;
    }

    @DynamoDBAttribute(attributeName = "mouth_open")
    public Boolean getMouthOpen() {
        return mouthOpen;
    }

    public void setMouthOpen(Boolean mouthOpen) {
        this.mouthOpen = mouthOpen;
    }

    @DynamoDBAttribute(attributeName = "emotions")
    public List<String> getEmotions() {
        return emotions;
    }

    public void setEmotions(List<String> emotions) {
        this.emotions = emotions;
    }

    @DynamoDBAttribute(attributeName = "landmarks")
    public List<String> getLandmarks() {
        return landmarks;
    }

    public void setLandmarks(List<String> landmarks) {
        this.landmarks = landmarks;
    }

    @DynamoDBAttribute(attributeName = "pose")
    public String getPose() {
        return pose;
    }

    public void setPose(String pose) {
        this.pose = pose;
    }

    @DynamoDBAttribute(attributeName = "image_quality")
    public String getImageQuality() {
        return imageQuality;
    }

    public void setImageQuality(String imageQuality) {
        this.imageQuality = imageQuality;
    }

    @DynamoDBAttribute(attributeName = "confidence")
    public Float getConfidence() {
        return confidence;
    }

    public void setConfidence(Float confidence) {
        this.confidence = confidence;
    }
}
